server:  port: 8099  servlet:    context-path: /        spring:
  application:
    name: querydsl-test  http:    encoding:
      force-request: true      charset: UTF-8  datasource:
    type: com.zaxxer.hikari.HikariDataSource    url: jdbc:mysql://127.0.0.1:3306/toby_test?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&autoReconnect=true&failOverReadOnly=false&useSSL=false&serverTimezone=UTC
    username: root
    password: nicai123
    driver-class-name: com.mysql.jdbc.Driver    hikari:
      maximum-pool-size: 50
      minimum-idle: 10
      connection-timeout: 6000
      connection-test-query: SELECT 1      auto-commit: true