spring:
  application:
    name: querydsl-test
  datasource:    url: jdbc:mysql://127.0.0.1:3306/toby_test?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&autoReconnect=true&failOverReadOnly=false&useSSL=false&serverTimezone=UTC
    username: root
    password: nicai123
    driver-class-name: com.mysql.jdbc.Driver
    hikari:      maximum-pool-size: 60
      